# This is a basic workflow to help you get started with Actions

name: Create azure_vm in various envs
on:
  push:
    branches: dev
jobs:
  review:
    runs-on: self-hosted
    environment: review
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
 
      - name: azure view deployment changes
        run: az deployment group what-if --resource-group newrg --template-file apim.bicep
   
  DEV:
    runs-on: self-hosted
    environment: dev
    needs: review
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
 
      - name: create azure_vm in DEV ENV 
        run: az deployment group create --resource-group newrg --template-file apim.bicep
    
  
  QA:
    runs-on: self-hosted
    environment: qa
    needs: DEV
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
          
      - name: create azure_vm in DEV ENV 
        run: az deployment group create --resource-group newrg --template-file apim.bicep
      
  Pre-pod:
    runs-on: self-hosted
    environment: Pre-pod
    needs: QA
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
          
      - name: create pre-prod folder
        run: mkdir pre-prod
     
     
     
          



